### ISSUE TITLE
Section Interfaces Omitted from TOSCA Template

### ISSUE THREAD

**Issue by gmolto** [indigo-dc/orchestrator#181]
Hi,

We are deploying the following TOSCA Template [cellar_webapp_mem_aws.yaml](https://github.com/indigo-dc/tosca-types/blob/devel/examples/cellar_webapp_mem_aws.yaml) through the Orchestrator in order to deploy it on AWS.

The infrastructure reaches the CREATE_COMPLETE status but the application is not deployed. After some debugging, we identified that the IM receives a modified TOSCA template that does not include the "interfaces" section for the "apache" node. 

To be clear, the Orchestrator receives this information for the "apache" node:

node_templates:
    apache:
      type: tosca.nodes.WebServer.Apache
      requirements:
        - host: web_server
      interfaces:
        Standard:
          configure:
            implementation: https://raw.githubusercontent.com/indigo-dc/tosca-types/master/artifacts/webapps/cellar-mem.yml
            inputs:
              download_url: { get_input: download_url }

But it passes down to the IM the following information for the "apache" node:

apache:
     type: tosca.nodes.WebServer.Apache
     requirements:
       - host: web_server   

Therefore, the "interfaces" section is missing, what prevents from installing the application. I guess that this information is somewhat lost during some parsing process of the TOSCA template.

The expected behaviour is that the full definition of the "apache" node is maintained in the TOSCA template submitted to the IM from the Orchestrator.

**Comment by alberto-brigandi** [comment]
Hi,
it should be fixed now.
I've tested it deploying on openstack and it's working correcly

**Comment by gmolto** [comment]
Works fine now in AWS. Thank you.
