### ISSUE TITLE
Error deleting infrastructure

### ISSUE THREAD

**Issue by alpegon** [indigo-dc/orchestrator#191]
Hi, I'm trying to delete an infrastructure created using the orchestrator and I'm getting this error:
{
  "code": 500,
  "title": "Internal Server Error",
  "message": "JTA transaction unexpectedly rolled back (maybe due to a timeout); nested exception is javax.transaction.RollbackException: ARJUNA016053: Could not commit transaction."
}

**Comment by alberto-brigandi** [comment]
Hi Alfonso,
which deployment? 3d23e076-327c-42fd-99bb-5ed10772caeb?

**Comment by alpegon** [comment]
Hi, the id is:

2a3036ac-6144-40ca-b50d-8a26abada731

**Comment by alpegon** [comment]
Hi Alberto, it's happening again with another infrastructure, the id is:

1950459e-9904-41d3-a7bc-fa36c7a26e0c

**Comment by alpegon** [comment]
Now It's working fine, thanks.
