### ISSUE TITLE
Deploying on EGI FedCloud without IAM - is this possible?

### ISSUE THREAD

**Issue by alahiff** [indigo-dc/orchestrator#253]
I've deployed a test orchestrator instance following the instructions (https://github.com/indigo-dc/orchestrator/blob/master/gitbook/how_to_deploy.md) along with a local infrastructure manager and cloud provider ranker. For the other required services I'm using the default external services.

I've tried deploying some VMs on EGI FedCloud using Orchent and one of the example TOSCA files, but I get this error:
```
2018-02-12 12:37:38.964 ERROR req-45a3757b-2f92-4093-9cec-6ef615a3de98 1 --- [pool-1-thread-8] i.r.o.s.commands.BaseWorkflowCommand     : Error deploying

it.reply.orchestrator.exception.OrchestratorException: No Authentication info provided for for Infrastructure Manager and OAuth2 authentication is disabled
```
Is it possible to deploy VMs on FedCloud via orchestrator without involving IAM? If so, where does IM get the cloud credentials from? When using IM on it's own I'm just using an authorisation file of course. Sorry of this is a basic question - I couldn't find anything in the documentation about this.

**Comment by alahiff** [comment]
Note that since submitting this ticket I obtained access to https://iam-test.indigo-datacloud.eu. Even with access to an IAM instance, how do I provide to Orchestrator the credentials needed to privision VMs on EGI FedCloud?

Various INDIGO presentations and tutorials (e.g. https://github.com/infn-bari-school/indigo-paas-tutorial/wiki) talk about obtaining a token then using Orchent, however I'm not able to obtain a token from IAM.

**Comment by maricaantonacci** [comment]
Dear @alahiff,
you can follow this [guide](https://github.com/indigo-dc/tosca-templates/blob/master/doc/tosca-deploy.md#2-obtaining-an-iam-token) on how to obtain a IAM token.

As far as I understand, you didn't install the whole INDIGO PaaS stack and therefore you might experience other problems trying to submit a deployment. Please note that a comprehensive guide for deploying and using the PaaS is being prepared and will be ready for the EOSCHUB-AHM. In the meantime you can contact me by email to get further details and support.

Best regards,
Marica

**Comment by alahiff** [comment]
Dear @maricaantonacci,

Thanks for your reply. I'll close this issue now and use email for any further questions.

Regards,
Andrew.
