### ISSUE TITLE
OCCI only seems to be partially supported

### ISSUE THREAD

**Issue by alahiff** [indigo-dc/orchestrator#263]
Some parts of the code seem to support OCCI, but other parts do not. For example in getIaasAuthHeader in src/main/java/it/reply/orchestrator/service/deployment/providers/factory/ImClientFactory.java OCCI is missing, which leads to errors like:

java.lang.IllegalArgumentException: Unsupported provider type <OCCI>
	at it.reply.orchestrator.service.deployment.providers.factory.ImClientFactory.getIaasAuthHeader(ImClientFactory.java:239)

**Comment by alahiff** [comment]
At the ESOC-Hub tech talk last week Enol mentioned that OCCI is being deprecated, as Marica had told me a few weeks ago. It may be good to completely remove OCCI in order to avoid any confusion.

**Comment by maricaantonacci** [comment]
OCCI is no longer supported.
