### ISSUE TITLE
Error getting non basic types in outputs

### ISSUE THREAD

**Issue by micafer** [indigo-dc/orchestrator#282]
Hi,

If I try to submit a TOSCA document like that:

https://github.com/indigo-dc/tosca-types/blob/master/examples/deep-plants-classification.yaml

But changing the outputs value to this:

```
  outputs:
    ports: 
      value: { get_attribute : [ docker_runtime, host, publish_ports ] }
```

The deployment is successfully deployed but the outputs are not correctly returned.It returns this error message:

```
"outputs":{
"ports": "Failed to evaluate function outputs[ports][value][get_attribute][docker_runtime, host, publish_ports]: no value found"
},
```

**Comment by alberto-brigandi** [comment]
Hi Miguel,
it's true; the logic backing the `get_attribute` value resolution is quite naive right now.

What kind of output do you need? Would something like this be ok for you?
```
"outputs": {
  "ports": [
    {
      "protocol": "tcp",
      "source": "5000",
      "target": "80"
    },
    {
      "protocol": "tcp",
      "source": "6000",
      "target": "443"
    }
  ]
}
```

**Comment by micafer** [comment]
Hi Alberto,

This output will be perfect.

**Comment by gmolto** [comment]
Is there any progress in this regard? We need this functionality implemented at your earliest convenience. Thank you in advance.

**Comment by maricaantonacci** [comment]
#330
