### ISSUE TITLE
Bad image specification for AWS deployment

### ISSUE THREAD

**Issue by maricaantonacci** [indigo-dc/orchestrator#377]
In file `/src/main/java/it/reply/orchestrator/service/ToscaServiceImpl.java`, the function `generateImImageUri()` returns a bad image url.

`return String.format("aws://%s", host);`

should be:

`return String.format("aws://%s", imageId);`

**Comment by alberto-brigandi** [comment]
closed by e6545d8da090a1d6c114f2fa302922c788c34130
