### ISSUE TITLE
#3095 Align security filter error response to those returned by the REST controllers

### ISSUE THREAD

**Issue by alberto-brigandi** [indigo-dc/orchestrator#38]
As now the response body if the authentication token is invalid is different from those that are returned from the REST controllers in case of errors.

e.g. if the token is invalid the response is

```
{
  "error": "invalid_token",
  "error_description": "Invalid token: <TOKEN>"
}
```

instead of

```
{
  "code": 401,
  "title": "Unauthorized",
  "message": "Invalid token: <TOKEN>"
}
```

**Comment by alberto-brigandi** [comment]
In order to resolve this issue is better to wait until spring-projects/spring-security-oauth#605 is closed, because as right now we'd have reimplement a lot of library classes

**Comment by bwegh** [comment]
what about changing the error, at least for this version to 
```
{
  "error":"the title",
  "error_description":"the message"
}
```
I do not really see a reason for the code as it gets returned by HTTP anyway
