### ISSUE TITLE
TOSCA: required inputs with default value not handled correctly

### ISSUE THREAD

**Issue by alberto-brigandi** [indigo-dc/orchestrator#73]
- [x] Required input not given by user, but with default value, should not throw error (i.e. only `required`, `not given`, `without default value` inputs should throw validation error).
- [x] Not valued input replacement should throw error (i.e. `not given` and `without default value`, but used in a `get_input` function in the template).

**Comment by lorenzo-biava** [comment]
*WARNING*: input replacement with a `null` value (i.e. a `not required` input, `not given` and `without default value`) should invoke the node property default behavior (i.e. replacing it with its `default` value or throwing error in it is a `required` property).
This is blocked by the Alien4Cloud current implementation (the node properties validation is done before we get the template...).
